source "https://rubygems.org"

gem "cuba"
gem "cuba-contrib"
gem "faker"
gem "mote"
gem "ohm"
gem "ohm-contrib"
gem "rack-protection"
gem "scrivener"
gem "scrivener_errors"
gem "shield"

group :development do
  gem "shotgun"
end
